[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; 使用自定义的极限双 OTA 分区
board_build.partitions = src/partitions.csv

build_flags = 
    -Os                             ; 极致代码体积优化
    -DCORE_DEBUG_LEVEL=0            ; 关闭调试日志减小体积
    -DCONFIG_BT_BLE_42_FEATURES_SUPPORTED=0 ; 关闭冗余特性

lib_deps = 
    https://github.com/pschatzmann/ESP32-A2DP.git
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.5
    adafruit/Adafruit SHT31 Library @ ^2.2.2
    Wire
    SPI

upload_port = /dev/cu.usbserial-110
monitor_port = /dev/cu.usbserial-110