[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps =
    C:/Users/37458/Documents/Arduino/libraries/lvgl
    C:/Users/37458/Documents/Arduino/libraries/Adafruit_ST7735_and_ST7789_Library
    C:/Users/37458/Documents/Arduino/libraries/Adafruit_MCP23017_Arduino_Library
    C:/Users/37458/Documents/Arduino/libraries/Adafruit_GFX_Library
    C:/Users/37458/Documents/Arduino/libraries/Adafruit_BusIO
    C:/Users/37458/Documents/Arduino/libraries/JPEGDEC

build_flags =
    -DCORE_DEBUG_LEVEL=4
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DLV_CONF_PATH="E:/ai-project/mx9.0/archives/6.0/lvgl_s3/src/lv_conf.h"
    "-IC:/Users/37458/Documents/Arduino/libraries/Adafruit_GFX_Library"
    "-IC:/Users/37458/Documents/Arduino/libraries/Adafruit_ST7735_and_ST7789_Library"
    "-IC:/Users/37458/Documents/Arduino/libraries/Adafruit_MCP23017_Arduino_Library/src"
    "-IC:/Users/37458/Documents/Arduino/libraries/Adafruit_BusIO"
    "-IC:/Users/37458/Documents/Arduino/libraries/ArduinoJson/src"
    "-IC:/Users/37458/Documents/Arduino/libraries/JPEGDEC/src"

upload_speed = 921600
monitor_filters = esp32_exception_decoder

[env:esp32-s3-devkitc-1_debug]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps =
    C:/Users/37458/Documents/Arduino/libraries/lvgl
    C:/Users/37458/Documents/Arduino/libraries/Adafruit_ST7735_and_ST7789_Library
    C:/Users/37458/Documents/Arduino/libraries/Adafruit_MCP23017_Arduino_Library
    C:/Users/37458/Documents/Arduino/libraries/Adafruit_GFX_Library
    C:/Users/37458/Documents/Arduino/libraries/Adafruit_BusIO
    C:/Users/37458/Documents/Arduino/libraries/JPEGDEC

build_flags =
    -DCORE_DEBUG_LEVEL=5
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DLV_CONF_PATH="E:/ai-project/mx9.0/archives/6.0/lvgl_s3/src/lv_conf.h"
    -DLV_LVGL_H_INCLUDE_SIMPLE=1
    "-IC:/Users/37458/Documents/Arduino/libraries/Adafruit_GFX_Library"
    "-IC:/Users/37458/Documents/Arduino/libraries/Adafruit_ST7735_and_ST7789_Library"
    "-IC:/Users/37458/Documents/Arduino/libraries/Adafruit_MCP23017_Arduino_Library/src"
    "-IC:/Users/37458/Documents/Arduino/libraries/Adafruit_BusIO"
    "-IC:/Users/37458/Documents/Arduino/libraries/ArduinoJson/src"
    "-IC:/Users/37458/Documents/Arduino/libraries/JPEGDEC/src"

upload_speed = 921600
monitor_filters = esp32_exception_decoder
